export const AUTH_ERROR_CODES = {
    SESSION_EXPIRADA: 'SESSION_EXPIRADA',
    TOKEN_EXPIRADO: 'TOKEN_EXPIRADO',
    TOKEN_INVALIDO: 'TOKEN_INVALIDO',
    TOKEN_CLIENTE_EXPIRADO: 'TOKEN_CLIENTE_EXPIRADO',
    TOKEN_CLIENTE_INVALIDO: 'TOKEN_CLIENTE_INVALIDO',
    REFRESH_TOKEN_EXPIRADO: 'REFRESH_TOKEN_EXPIRADO',
    REFRESH_TOKEN_INVALIDO: 'REFRESH_TOKEN_INVALIDO',
    CONEXION_SERVIDOR_REQUERIDA: 'CONEXION_SERVIDOR_REQUERIDA',
    USER_ALREADY_LOGGED_IN: 'USER_ALREADY_LOGGED_IN',
} as const;