export const whitelist = {
    vistas: [
        {
            nombre: "View_VentasConProducto",
            descripcion: "Detalle de productos por venta, útil cuando el usuario pide información con producto, marca o cantidad.",
            camposPermitidos: [
                "Serie",
                "Folio",
                "Fecha",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Estado",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "CostoProducto",
                "ImporteProducto",
                "Vendedor",
                "Familia",
                "Grupo",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario",
            ],
            orderBy: "Folio"

        },
        {
            nombre: "View_VentasConTotales",
            descripcion: "Totales por factura o venta; usar cuando el usuario pide resumen o totales.",
            camposPermitidos: [
                "Fecha",
                "Serie",
                "Folio",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "FormaPago",
                "Vendedor",
                "DiasCredito",
                "Almacen",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario",
            ],
            orderBy: "Folio"
        },
        {
            nombre: "View_ComprasConProducto",
            descripcion: "Compras con detalle de producto; usar si el usuario menciona código, marca, familia o grupo.",
            camposPermitidos: [
                "Folio",
                "Fecha",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "EstadoDocumento",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "ImporteProducto",
                "Familia",
                "Grupo",
                "Usuario"
            ],
        },
        {
            nombre: "View_ComprasConTotales",
            descripcion: "Resumen general de compras; usar si el usuario no menciona productos ni marcas.",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FolioProveedor",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "DiasCredito"
            ],
        },
    ],
};