export const whitelist: { vistas: { nombre: string; descripcion: string; camposPermitidos: string[]; orderBy?: string, categoria?: string }[] } = {
    vistas: [
        {
            nombre: "View_VentasConProducto",
            descripcion: "Detalle de productos por venta, útil cuando el usuario pide información con producto, marca o cantidad.",
            camposPermitidos: [
                "Serie",
                "Folio",
                "Fecha",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Estado",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "CostoProducto",
                "ImporteProducto",
                "Vendedor",
                "Familia",
                "Grupo",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario",
            ],
            orderBy: "Folio"

        },
        {
            nombre: "View_VentasConTotales",
            descripcion: "Totales por factura o venta; usar cuando el usuario pide resumen o totales.",
            camposPermitidos: [
                "Fecha",
                "Serie",
                "Folio",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "FormaPago",
                "Vendedor",
                "DiasCredito",
                "Almacen",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario",
            ],
            orderBy: "Folio"
        },
        {
            nombre: "View_ComprasConProducto",
            descripcion: "Compras con detalle de producto; usar si el usuario menciona código, marca, familia o grupo.",
            camposPermitidos: [
                "Folio",
                "Fecha",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "EstadoDocumento",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "ImporteProducto",
                "Familia",
                "Grupo",
                "Usuario"
            ],
        },
        {
            nombre: "View_ComprasConTotales",
            descripcion: "Resumen general de compras; usar si el usuario no menciona productos ni marcas.",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FolioProveedor",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "DiasCredito"
            ],
        },
        {
            nombre: "View_Clientes",
            descripcion: "Información detallada de clientes; usar cuando el usuario solicita datos específicos de clientes.",
            camposPermitidos: [
                "Almacen",
                "NumeroCliente",
                "FechaAlta",
                "NombreCliente",
                "RazonSocial",
                "RFC",
                "Calle",
                "NoExt",
                "NoInt",
                "Colonia",
                "Ciudad",
                "Estado",
                "CodigoPostal",
                "Telefono1",
                "Telefono2",
                "Correo",
                "FormadePago",
                "TipodeCliente",
                "Vendedor",
                "ListadePrecios",
                "LimitedeCredito",
                "DiasdeCredito",
                "Descuento"
            ]
        },
        {
            nombre: "View_Cobranza",
            descripcion: "Información detallada de cobranza; usar cuando el usuario solicita datos específicos de cobranza o pagos.",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FechaOperacion",
                "NumeroOperacion",
                "Importe",
                "NombreCliente",
                "Paridad",
                "Descripcion",
                "EstadoAbono",
                "FormaPago",
                "Vendedor",
                "Almacen",
                "Usuario"
            ]
        },
        {
            nombre: "View_ComprasconProducto",
            descripcion: "Detalle de productos por compra, útil cuando el usuario pide información con producto, marca o cantidad.",
            camposPermitidos: [
                "Folio",
                "Fecha",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "EstadoDocumento",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "ImporteProducto",
                "Familia",
                "Grupo",
                "Usuario"
            ],
        },
        {
            nombre: "View_ComprasconTotales",
            descripcion: "Compras con solo Totales, ordenes de compra. No incluye campo FormaPago.",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FolioProveedor",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "DiasCredito",
                "Usuario"
            ]
        },
        {
            nombre: "View_CuentasPorCobrar",
            descripcion: "Información de cuentas por cobrar; usar cuando el usuario solicita datos sobre saldos pendientes de clientes.",
            camposPermitidos: [
                "Fecha",
                "Serie",
                "Folio",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "Vendedor",
                "DiasCredito",
                "FechaVencimiento",
                "Almacen",
                "Usuario",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino"

            ]
        },
        {
            nombre: "View_Productos",
            descripcion: "Informacion del catalogo de productos, incluye Codigo, Descripcion, costo, Precio.",
            categoria: "Productos",
            camposPermitidos: [
                "Codigo",
                "Descripcion",
                "Familia",
                "Grupo",
                "Marca",
                "Observaciones",
                "FechaAlta",
                "UltimaEntrada",
                "UltimaSalida",
                "TipoProducto",
                "EstadodeProducto",
                "Unidad",
                "Costo",
                "Maximo",
                "Minimo",
                "Precio",
                "Factor",
                "ListaPrecios",
                "Existencia"
            ]
        },
        {
            nombre: "View_VentasconProducto",
            descripcion: "Detalle de ventas por producto, incluye Codigo, Descripcion, Cantidad, Precio, Importe.",
            categoria: "Ventas.Detalle",
            camposPermitidos: [
                "Folio",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Fecha",
                "Estado",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "Descripcion",
                "PrecioProducto",
                "CostoProducto",
                "PrecioProductoOriginal",
                "ImporteProducto",
                "Vendedor",
                "Familia",
                "Grupo",
                "Existencia",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario",
                "Almacen"
            ]
        },
        {
            nombre: "View_VentasconTotales",
            descripcion: "Totales por venta o factura, incluye Subtotal, Impuesto, Total, Saldo, FormaPago.",
            categoria: "Ventas.Totales",
            camposPermitidos: [
                "Fecha",
                "Serie",
                "Folio",
                "TipoDocumento",
                "NumeroCliente",
                "NombreCliente",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "CantDescuento",
                "Notas",
                "FormaPago",
                "Vendedor",
                "DiasCredito",
                "Almacen",
                "TipoDocumentoOrigen",
                "DocumentosOrigen",
                "TipoDocumentoDestino",
                "DocumentosDestino",
                "Usuario"
            ]
        },
        {
            nombre: "View_ExistenciasDeProductos",
            descripcion: "Existencias de productos, Inventario de Productos, Tock de Productos, Existencias de Mercancias.",
            categoria: "Existencia de Productos",
            camposPermitidos: [
                "Codigo",
                "Descripcion",
                "Familia",
                "Grupo",
                "Marca",
                "FechaAlta",
                "TipoDeProducto",
                "EstadodelProducto",
                "Unidad",
                "Costo",
                "MaximoEnInventario",
                "MinimoenInventario",
                "Precio",
                "Existencia",
                "Almacen"
            ]
        },
        {
            nombre: "View_AjustesDeInventario",
            descripcion: "Movimientos de Inventario generados en modulo inventarios.",
            categoria: "Movimientos de Inventario",
            camposPermitidos: [
                "Folio",
                "Fecha",
                "TipoDeMovimiento",
                "EstadoMovimiento",
                "CodigoProducto",
                "CantidadDeProducto",
                "Marca",
                "DescripcionProducto",
                "Familia",
                "Grupo",
                "Usuario"
            ]
        },
        {
            nombre: "View_Proveedores",
            descripcion: "Informacion del catalogo de proveedores, incluye numero, nombre, domicilio, correo.",
            categoria: "Proveedores",
            camposPermitidos: [
                "NumeroProveedor",
                "FechaAlta",
                "NombreProveedor",
                "RFC",
                "Calle",
                "NoExt",
                "NoInt",
                "Colonia",
                "Ciudad",
                "Estado",
                "CodigoPostal",
                "Telefono1",
                "Telefono2",
                "Correo",
                "TipodeProveedor",
                "DiasdeCredito"
            ]
        },
        {
            nombre: "View_CuentasPorPagar",
            descripcion: "Documentos de Compras a Credito como Facturas con saldo mayor que cero pendientes por pagar a Proveedores.",
            categoria: "Cuentas por Pagar",
            camposPermitidos: [
                "Fecha",
                "Serie",
                "Folio",
                "TipoDocumento",
                "NumeroProveedor",
                "NombreProveedor",
                "Subtotal",
                "Impuesto",
                "Total",
                "Saldo",
                "EstadoDocumento",
                "DiasCredito",
                "FechaVencimiento",
                "Almacen",
                "Usuario"
            ]
        },
        {
            nombre: "View_Pagos",
            descripcion: "Pagos a Proveedores de facturas de compra a credito o Gastos de la empresa.",
            categoria: "Pagos a Proveedores o Gastos",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FechaOperacion",
                "NumeroOperacion",
                "Importe",
                "NombreProveedor",
                "Paridad",
                "Descripcion",
                "ConceptoPago",
                "tipoGastoOperativo",
                "EstadoPago",
                "FormaPago",
                "Almacen",
                "Usuario"
            ]
        },
        {
            nombre: "View_GastosOperativos",
            descripcion: "Gatos Operativos de la Empresa, como Luz, renta, sueldos, etc.",
            categoria: "Gastos Operativos",
            camposPermitidos: [
                "Fecha",
                "Folio",
                "FechaOperacion",
                "NumeroOperacion",
                "Importe",
                "NombreProveedor",
                "Paridad",
                "Descripcion",
                "ConceptoPago",
                "tipoGastoOperativo",
                "EstadoPago",
                "FormaPago",
                "Almacen",
                "Usuario"
            ]
        },
        {
            nombre: "View_ComponentesPorProducto",
            descripcion: "Componenes de producto terminado, BOM, Lista de Materiales de PT.",
            categoria: "Componentes de Produtos",
            camposPermitidos: [
                "CodigoProductoTerminado",
                "ProductoTerminado",
                "CodigoComponente",
                "Componente",
                "Marca",
                "MarcaNombre",
                "CantidadPorUnidad",
                "Existencia"
            ]
        }

    ],
};